name: Hassfest

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
